VERZIJA=CDX
MODUL=VIRM

PRGS=../main/1g/e.prg
CS=
ASMS=

FMK_LIBS=fmk_roba.lib fmk_svi.lib fmk_pi.lib fmk_evn.lib fmk_sec.lib fmk_mes.lib fmk_rab.lib fmk_rn.lib fmk_lok.lib

SCLIB_LIBS=sc1g_arh.lib sc1g_ba.lib sc1g_cui.lib sc1g_db.lib sc1g_os.lib sc1g_ost.lib sc1g_par.lib sc1g_pr.lib sc1g_sif.lib sc1g_sql.lib sc1g_ut.lib sc2g_app.lib sc2g_db.lib sc1g_rpt.lib sc2g_cui.lib sc1g_key.lib

MODUL_LIBS=vi_1db.lib vi_2db.lib vi_1dok.lib vi_1ma.lib vi_2ma.lib vi_1par.lib vi_1rpt.lib vi_1sif.lib vi_1raz.lib

include $(SC_BUILD_HOME_DIR)/sclib/Makefile_clipper

